name: dnaiq
favicon: null
layout_spectrum: 0.7545296766329557
typography_spectrum: 0.5526240412145853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09502785792574286
  lightness: 0.390214646467939
  saturation: 0.3888813110534102
  rhythmicContrast: 0.9346894992049783
purpose: []
